Development:
  ###
  # This parameter is used to activate or deactivate the debug mode.
  DEBUG_FLAG: 0             # 1 ... activate 0 ... deactivate

Security:
  ###
  # This parameter specifies the path tp the certificate file needed to provide vhh-mmsi api access.
  PEM_PATH: "/home/dhelm/VHH_Develop/certificates/cacert.pem"  # certificate file for vhh-mmsi api access

ApiEndpoints:
  ###
  # This parameter specifies the root url for the RestApi endpoints.
  ROOT_URL: "https://api.vhh-stg.max-recall.com/api/shotservice/"   # root url for API endpoints

VhhCore:
  ###
  # This parameter specifies the video download path.
  VIDEO_DOWNLOAD_PATH: "/data/share/maxrecall_vhh_mmsi/videos/downloaded/"   # directory to store all downloaded videos

  ###
  # This parameter is used to activate/deactivate the clean-up mode. The clean-up mode deletes all downloaded videos and the corresponding generated results.
  CLEANUP_FLAG: 0   # 0 ... deactivate cleanup function OR 1 ... activate cleanup method -> delete all downloaded videos + annotation results locally

  ###
  # This parameter specifies the results path for each individual plugin.
  RESULTS_ROOT_DIR: "/data/share/maxrecall_vhh_mmsi/videos/results/"

PluginConfigs:
  ###
  # This parameter specifies the configuration path (.yaml) for the shot boundary detection plugin module
  SBD_CONFIG_FILE: "/home/dhelm/VHH_Develop/pycharm_vhh_core/config/SBD/config_single_video.yaml"

  ###
  # This parameter specifies the configuration path (.yaml) for the shot type classification plugin module
  STC_CONFIG_FILE: "/home/dhelm/VHH_Develop/pycharm_vhh_core/config/STC/config_single_video.yaml"

  ###
  # This parameter specifies the configuration path (.yaml) for the camera movement classification module
  CMC_CONFIG_FILE: "None"





